### ISSUE TITLE
DOMXPath error codes

### ISSUE THREAD

**Issue by math-ematics** [janreges/siteone-website-crawler#3]
I installed the new version of the crawler to test it out.
I were using the earlier where you used swoole-cli and loaded crawler,php to start it.

With the new I am crawling the same site i manage. Its 1500 pages.

Warning: DOMXPath::query(): Invalid predicate in /root/tools/crawler2/siteone-website-crawler/src/Crawler/Analysis/AccessibilityAnalyzer.php on line 195

Warning: Attempt to read property "length" on bool in /root/tools/crawler2/siteone-website-crawler/src/Crawler/Analysis/AccessibilityAnalyzer.php on line 197

Warning: DOMXPath::query(): Invalid predicate in /root/tools/crawler2/siteone-website-crawler/src/Crawler/Analysis/AccessibilityAnalyzer.php on line 195

Warning: Attempt to read property "length" on bool in /root/tools/crawler2/siteone-website-crawler/src/Crawler/Analysis/AccessibilityAnalyzer.php on line 197

**Comment by math-ematics** [comment]
This is repeating alot during the same crawl.

I am on Ubuntu

**Comment by janreges** [comment]
If you try `git pull` the current version it should be fixed. Still, I'd appreciate an email URL to explore your HTML further.

**Comment by math-ematics** [comment]
You have an email now

Den tis 21 nov. 2023 18:05Ján Regeš ***@***.***> skrev:

**Comment by janreges** [comment]
Thank you @math-ematics.

As I wrote to you in the e-mail, I made several improvements in the latest version based on your use-case.

One of them was adding `--regex-filtering-only-for-pages` parameter.
